### ISSUE TITLE
Create a Website it should be able to tell Weather in the particular area

### ISSUE THREAD

**Issue by sohilkhanduja** [sohilkhanduja/Hacktober-Fest#2]
For reference Developers can use this https://www.accuweather.com/en/in/delhi/202396/weather-forecast/202396

**Comment by sohilkhanduja** [comment]
Sure @saaiiravi. Assigning this to you go ahead.

**Comment by saaiiravi** [comment]
Hi @sohilkhanduja 

Please review my PR for this issue.

**Comment by sohilkhanduja** [comment]
I have reviewed it and merged it @saaiiravi. It's working properly in the backend but its design could have been more beautiful. You could have used CSS. Overall a great work was done. Thanks for your contribution.
