### ISSUE TITLE
Create a program in C++/C for all linked list operations

### ISSUE THREAD

**Issue by sohilkhanduja** [sohilkhanduja/Hacktober-Fest#8]

**Comment by saurabh042** [comment]
Hi @sohilkhanduja 
can i pick this one?

**Comment by sohilkhanduja** [comment]
> Hi @sohilkhanduja can i pick this one?

Hi, @saurabh042 Let me know about the language in which you are going to do it and then I will assign you.

**Comment by yashneet-kalra** [comment]
Hi, @sohilkhanduja , I can do this in C Language. Can you assign me this one please?

**Comment by sohilkhanduja** [comment]
Sure, you can do it @yashneet-kalra . Assigning you this task.

**Comment by ayushpaine** [comment]
Hi, I can do this in C++, can you please assign this to me?

**Comment by saurabh042** [comment]
HI @sohilkhanduja  Can I do it in C++?

**Comment by sohilkhanduja** [comment]
I will check it and revert to you soon @saurabh042.
